#pragma once

#define VIAL_KEYBOARD_UID {0xE0, 0xEC, 0xE4, 0x95, 0x6C, 0x8D, 0xE2, 0x62}

#define VIAL_UNLOCK_COMBO_ROWS {1,1}
#define VIAL_UNLOCK_COMBO_COLS {0,9}

#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define VIAL_TAP_DANCE_ENTRIES 10
#define VIAL_COMBO_ENTRIES 10
